### ISSUE TITLE
Swag?

### ISSUE THREAD

**Issue by cdcme** [nodeschool/portland-me#11]
We have (spoiler alert!) stickers already but I'm interested to know what people might like to see in the future.

**Comment by jaegerpicker** [comment]
We should check with O'Reilly books, they sponsored the meetup I ran in Ohio and we gave away free books, plural site is a online training site that also sponsored free trial cards there.

**Comment by cdcme** [comment]
Nice!

**Comment by jaegerpicker** [comment]
I have an email into O'Reilly, I'll update it back after I hear back.

**Comment by jonny4475** [comment]
I used to attend a .NET users group at UNUM that disbanded a year or two
ago. I believe ProSearch used to provide food (pizza, sandwiches) for the
monthly meetings. They (or another job placement agency) may be a resource
to consider.

**Comment by ghost** [comment]
Any sponsor swag (shrits, mugs, etc.) are always nice but for me this is about learning something new and hopefully learning enough to be dangerous - swag or no swag.
