### ISSUE TITLE
State of things?

### ISSUE THREAD

**Issue by devinivy** [nodeschool/portland-me#14]
Hey!  Node dev in Portland here.  Are there any plans in the pipeline?  How many people helped put on the first event?  Is more help needed?  Just checking-in!

**Comment by cdcme** [comment]
Hi, @devinivy - we are planning the next workshop now. We're looking pretty hard at the weekend of July 11th-12th but haven't sent out a notification yet. If you haven't already, join the Meetup at http://www.meetup.com/nodeschool-portland-me and check out our site at http://nodeschool.io/portland-me for more info.
