### ISSUE TITLE
What would be the best day to have the first workshop?

### ISSUE THREAD

**Issue by cdcme** [nodeschool/portland-me#3]
Keep in mind that a weekday might result in higher turnout but would give us less time to cover material while a weekend might result in a lower turnout but would definitely give us a lot more time to cover more and to cover those items in more depth.

**Comment by jaegerpicker** [comment]
I actually think I like the idea of a Saturday Afternoon, I'm almost always busy in the morning but a Saturday 2-6 or so might be worthwhile. Especially if we phrase it as an indepth workshop.

**Comment by jbane** [comment]
I like Saturday afternoon as well.

**Comment by jasonrhodes** [comment]
Butting in... we've had a lot of success in Baltimore with Sunday afternoons. Weekday nights just don't seem like enough time to do anything worthwhile, in my opinion. We usually do 1-5pm on Sundays. We tried 1-5pm on a Saturday once and got lower turnout, but that's a very small sample size.

Good luck!

**Comment by jonny4475** [comment]
Saturday works better for the near future from my perspective, fwiw.

**Comment by ghost** [comment]
Sundays would be OK, however once the weather turns for the better that might not work so well.  Also weekends for folks with families (like me) can be tough to devote to non-familiy activities.  In the summer I'd almost never be able to attend on a weekend as we go camping up in Hancock county.  A weekday would give me a good reason to disconnect from work at a reasonable hour (and my employer would like that I am expanding my horizons).  I'd be open for a weekday that runs 7-10PM perhaps?  If a weekday Thursday or even Friday would be decent.

Thanks

**Comment by cdcme** [comment]
@jasonrhodes Awesome, thanks!

@jonny4475, @shepp67 Yeah, I mean, obviously it'll be impossible to accommodate everyone but we'll try to settle on a day/time when most people feel like they could probably attend and go from there. Right now, it seems like Sunday afternoon is a pretty good option.

**Comment by cdcme** [comment]
Also, how much lead time is reasonable? 2 weeks or a month?

**Comment by ghost** [comment]
2 weeks should be good.  How many people have signed up so far Carlo?

Shepp

**Comment by cdcme** [comment]
@shepp67 We have 23 people on Meetup, but we'll have to wait and see how many people RSVP to the event.

**Comment by a0viedo** [comment]
Here in Buenos Aires we do Saturdays from 3 to 6pm, but only because Sundays are historically the day of the week when you spend time with your family.

**Comment by cdcme** [comment]
@a0viedo Well, it's interesting because _traditionally_ that's true in the US, too - even across cultures - but in some regions, like the West Coast and Northeast, I feel like that's a little bit less of a thing and more people are starting to see Sundays as a general socialization day. I think whether or not the person is single and/or has family in the area (I think we tend move around a lot more than is common elsewhere) also both play a role. Seems like perfect material for some sociological studies!

All that being said, if anyone wants to bring family, that would be awesome - the more the merrier!

**Comment by ghost** [comment]
Quick question; I've got a 12-year old daughter that shows interest in learning programming, would this be an appropriate setting for her?  If not it's cool :)
Thanks!

Joel

Joel

One life, one chance, one ticket to the big dance.

**Comment by cdcme** [comment]
@shepp67 I don't have a problem with that but let me check with the venue and get back to you.

**Comment by cdcme** [comment]
@shepp67 from the venue people: "Just so long as they abide the rules and are not roving about the space.  Perhaps just let them know the mezzanine is for members only."

So, yes!

**Comment by ghost** [comment]
Cool! If she is interested I'll bring her along.  :)

Thx man!
Joel 

Joel

One life, one chance, one ticket to the big dance.

**Comment by ghost** [comment]
What's the parking situation in this area anyway?  I'm coming in from SE NH
in a full-size p/u truck and don't know the area at all.  Google street
view looks like only on-street parking.  Any lots or garages nearby?

W

**Comment by cdcme** [comment]
Sure are! See the [listing here](http://www.portlandmaine.com/getting-around/parking/#garages) or the [map here](https://www.google.com/maps/d/u/0/viewer?msa=0&mid=zHIwwcXmkGdg.kqawVN8POi_I).

**Comment by ghost** [comment]
Cool!

Hey I just noticed this workshop is not listed on the nodeschool.io events
calendar, its a shame b/c on the home page they have upcoming events...

http://nodeschool.io/events.html

Shepp

**Comment by ghost** [comment]
Carlo do you have any prereq's in mind before the event?  E.g. install
node, install learnyounode, etc.?

Thanks!

Shepp

**Comment by cdcme** [comment]
Thanks for pointing that out - we're on there now!

Sure, you can [join the meetup](http://www.meetup.com/nodeschool-portland-me/), RSVP, and prereqs are listed in the event description.

**Comment by ghost** [comment]
(doh) - already RSVP, just read the pre-reqs.

Thanks!
Joel

**Comment by ghost** [comment]
Unfortunately ice age 2015 will keep me from attending today's workshop, I'll keep my eye out for a future event.  

Good luck and hope everyone crushes it today at the workshop!

Best,

Joel

One life, one chance, one ticket to the big dance.
