### ISSUE TITLE
What would be the best time (amount and hour) to have the first workshop?

### ISSUE THREAD

**Issue by cdcme** [nodeschool/portland-me#4]
If we do it on a weekday, the absolute **most** we can hope for is 2 hours, and that's pushing it. If we can get everybody's buy-in on doing it on a Saturday, though, we can probably do a 4-hour workshop, which is really the ideal IMHO.

**Comment by ghost** [comment]
How often are you planning to meet Carlo?  Monthly?
I'd be up for something like 7-10PM for a weeknight and 2-6 or 3-7PM on a weekend (Sunday), or super early on a weekend could also be a good alternative.  Maybe 7-10 or 11AM.

**Comment by cdcme** [comment]
@shepp67 Well, given the workshop format, I don't think we'll be doing regularly scheduled meetups, at least at first. My goal right now is to just pull off _one_ successful workshop, then think about what to do next. :D
