### ISSUE TITLE
What should we cover in the first workshop and how much?

### ISSUE THREAD

**Issue by cdcme** [nodeschool/portland-me#6]
To find this out, we need to gauge the group's JS/Node proficiency and try to provide a good first experience tailored to that baseline. I think it's important not to burn through time with things everybody is already familiar with but that it's equally important that we don't make any assumptions there...

I feel like the workshops can logically be broken up into rough categories of JS programming, Node, and advanced topics. Maybe for the first one we can cover all or some of the JS ones (javascripting, planet proto, functional js, & lodash)? My only concern is that although it's important to have a good base in these, I'm afraid this might not be exciting enough for some people... Definitely should figure all that out.

**Comment by ghost** [comment]
For me I am at best an intermediate coder (I can scratch out some Ruby, Python, I understand OOP).  I'm not a developer nor do I have to code much at all as my profession (I am in QA however and want to really learn and apply coding to automate more).  I have zero node or even JS experience.

**Comment by cdcme** [comment]
Would it be helpful to do a pre-workshop meetup where we do a high-level overview (talk format) of Node, the ecosystem, etc.? I'm just thinking that this might help everyone start off on the same page when we do the first workshop...thoughts?

**Comment by ghost** [comment]
I'd suggest that be the first hour or first half of the inaugural  meetup the we get to  the good stuff (learning/mentoring). 

Joel 

Joel

One life, one chance, one ticket to the big dance.

**Comment by cdcme** [comment]
@shepp67 Yeah, that's a great compromise. First half-hour as an overview then into the hands-on bit.
