### ISSUE TITLE
Offline plan

### ISSUE THREAD

**Issue by cdcme** [nodeschool/portland-me#9]
we should have some thumb drives w/all the necessary software and modules on it that we can pass around if need be

**Comment by jaegerpicker** [comment]
Yeah, that's a good idea. I'll see about picking up a couple of cheap ones to handle that.

Software needed(?):
node/npm offline installer (mac/Linux/windows)
Atom editor (mac/linux/windows)
mean stack npm installed dir
mongodb
seed data for any exercises?
unit testing setup maybe
cygwin for windows?

Think of anything else?

**Comment by cdcme** [comment]
I have a couple of spare ones I can donate, too. If we have 15-20 attend _and_ we run into connectivity issues, I'm thinking we'll want at least 5 in rotation. Thoughts?

**Comment by fmoliveira** [comment]
@jaegerpicker  I'd add Robomongo, which is a great visual management tool for MongoDB available for Mac, Windows and Linux at http://robomongo.org/.
